name = "miscellaneousmathproblems"
version = "0.1.0"

[[lean_lib]]
name = "MagicSquareOfSquares"
srcDir = "magic-square-of-squares"
roots = ["MagicSquareOfSquares"]

[[lean_lib]]
name = "DiophantineY3X4"
srcDir = "diophantine-y3-x4"

[[lean_lib]]
name = "DiophantineY3yX4x4"
srcDir = "diophantine-y3y-x4x4"
roots = ["NonExistenceProof"]

[[lean_lib]]
name = "DivisorTauMax"
srcDir = "divisor-tau-max"
roots = ["DivisorTauMax"]

[[lean_lib]]
name = "DiophantineY2X3yZ4"
srcDir = "diophantine-y2-x3y-z4"
roots = ["NonExistenceProof"]

[[lean_lib]]
name = "DiophantineY3xyX4"
srcDir = "diophantine-y3xy-x4"
roots = ["NonExistenceProof"]

[[lean_lib]]
name = "QuadraticCyclicDiophantine"
srcDir = "quadratic_cyclic_diophantine"
roots = ["InfinitelyManySolutions"]

[[lean_lib]]
name = "DiophantineX5Y4Z2"
srcDir = "diophantine-x5y4-2z2"
roots = ["InfinitelyManySolutions"]

[[lean_lib]]
name = "DiophantineX5Y43Z2Zero"
srcDir = "diophantine-x5y4plus3z2-zero"
roots = ["InfinitelyManySolutions"]

[[lean_lib]]
name = "Diophantine2X4Y4Z3"
srcDir = "diophantine-2x4-y4plusz3"
roots = ["InfinitelyManySolutions"]

[[lean_lib]]
name = "DiophantineX4plus4Y3plusZ3"
srcDir = "diophantine-x4plus4y3plusz3"
roots = ["InfinitelyManySolutions"]

[[lean_lib]]
name = "DiophantineX4X2XYY3"
srcDir = "diophantine-x4-x2plusxyplusy3"
roots = ["FiniteSolutionsProof"]

[[lean_lib]]
name = "Diophantine3xm1y2xz2x3m2"
srcDir = "diophantine-3xm1y2plusxz2-x3m2"
roots = ["NonExistenceProof"]

[[lean_lib]]
name = "DiophantineR4SqConstraint"
srcDir = "diophantine-r4sq-constraint"
roots = ["ConstraintProof"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.21.0"
