#!/usr/bin/env python3
"""
brute_force_search.py — Integer solutions to x^5 + 2*y^3 + z^3 = 0

Performs an exhaustive search over |x|, |y|, |z| <= BOUND and records every
integer triple (x, y, z) satisfying the equation.

Additionally verifies the two parametric families:
  Family 1: (-t^3, t^5, -t^5)     for t in Z  [from setting z = -y]
  Family 2: (-t^3, 0,   t^5)      for t in Z  [from setting y = 0]

Both families are generated by the weighted homogeneity of the equation
with weights wt(x)=3, wt(y)=5, wt(z)=5 (each term has weighted degree 15).
"""

import sys
from typing import Generator

BOUND = 50  # Search |x|, |y|, |z| <= BOUND


# ── Core search ──────────────────────────────────────────────────────────────

def search_solutions(bound: int) -> list[tuple[int, int, int]]:
    """Return all (x, y, z) with max(|x|,|y|,|z|) <= bound satisfying the eq."""
    solutions: list[tuple[int, int, int]] = []
    for x in range(-bound, bound + 1):
        x5 = x ** 5
        for y in range(-bound, bound + 1):
            rhs = -x5 - 2 * y ** 3  # need z^3 = rhs
            # check if rhs is a perfect cube
            z = icbrt(rhs)
            if z is not None and abs(z) <= bound:
                solutions.append((x, y, z))
    return sorted(set(solutions))


def icbrt(n: int) -> int | None:
    """Return the integer cube root of n if it exists, else None."""
    if n == 0:
        return 0
    sign = 1 if n > 0 else -1
    a = abs(n)
    # Initial estimate via float
    r = round(a ** (1 / 3))
    for candidate in range(max(0, r - 2), r + 3):
        if candidate ** 3 == a:
            return sign * candidate
    return None


# ── Parametric family verification ───────────────────────────────────────────

def verify_family1(t_range: range) -> bool:
    """Check (-t^3, t^5, -t^5) for all t in t_range."""
    ok = True
    for t in t_range:
        x, y, z = -(t ** 3), t ** 5, -(t ** 5)
        val = x ** 5 + 2 * y ** 3 + z ** 3
        if val != 0:
            print(f"  Family 1 FAILS at t={t}: val={val}")
            ok = False
    return ok


def verify_family2(t_range: range) -> bool:
    """Check (-t^3, 0, t^5) for all t in t_range."""
    ok = True
    for t in t_range:
        x, y, z = -(t ** 3), 0, t ** 5
        val = x ** 5 + 2 * y ** 3 + z ** 3
        if val != 0:
            print(f"  Family 2 FAILS at t={t}: val={val}")
            ok = False
    return ok


# ── Main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    print("=" * 60)
    print("Brute-force search: x^5 + 2y^3 + z^3 = 0")
    print(f"  Search bound: |x|, |y|, |z| <= {BOUND}")
    print("=" * 60)

    # 1. Parametric-family verification
    t_check = range(-10, 11)
    print(f"\n[1] Verifying Family 1 (−t³, t⁵, −t⁵) for t in {list(t_check)[:3]}…{list(t_check)[-3:]}:")
    ok1 = verify_family1(t_check)
    print(f"    {'PASS' if ok1 else 'FAIL'}")

    print(f"\n[2] Verifying Family 2 (−t³, 0, t⁵) for t in {list(t_check)[:3]}…{list(t_check)[-3:]}:")
    ok2 = verify_family2(t_check)
    print(f"    {'PASS' if ok2 else 'FAIL'}")

    # 2. Exhaustive search
    print(f"\n[3] Exhaustive search for |x|,|y|,|z| <= {BOUND} …")
    sols = search_solutions(BOUND)
    print(f"    Found {len(sols)} solutions (including z=0 and negatives).")

    # Tally by family membership
    fam1 = [(x, y, z) for x, y, z in sols
            if y != 0 and z == -y and x == -(round(abs(y) ** (1/5)) ** 3) * (1 if y > 0 else -1)]
    fam2 = [(x, y, z) for x, y, z in sols if y == 0]

    # Better family tagging
    def in_family1(x: int, y: int, z: int) -> bool:
        if z != -y:
            return False
        t = icbrt(-x)
        return t is not None and t ** 5 == y

    def in_family2(x: int, y: int, z: int) -> bool:
        if y != 0:
            return False
        t = icbrt(-x)
        return t is not None and t ** 5 == z

    print(f"\n{'x':>8}  {'y':>10}  {'z':>10}  {'family'}")
    print("-" * 50)
    for x, y, z in sols:
        tag = []
        if in_family1(x, y, z):
            tag.append("Fam 1")
        if in_family2(x, y, z):
            tag.append("Fam 2")
        if x == 0 and y == 0 and z == 0:
            tag = ["trivial"]
        label = ", ".join(tag) if tag else "other"
        print(f"{x:>8}  {y:>10}  {z:>10}  {label}")

    # 3. Check for solutions outside the two families
    non_parametric = [
        (x, y, z) for x, y, z in sols
        if not in_family1(x, y, z) and not in_family2(x, y, z)
        and not (x == 0 and y == 0 and z == 0)
    ]
    if non_parametric:
        print(f"\n  Non-parametric solutions found ({len(non_parametric)}):")
        for s in non_parametric:
            print(f"    {s}")
    else:
        print(f"\n  All solutions within the search range are accounted for by"
              f" Family 1, Family 2, or the trivial solution (0,0,0).")

    print("\n[4] Small explicit seeds (direct check):")
    seeds = [
        (-1,  1, -1, "Family 1, n=1"),
        ( 1, -1,  1, "Family 1, n=-1"),
        (-1,  0,  1, "Family 2, n=1"),
        ( 1,  0, -1, "Family 2, n=-1"),
        (-8, 32,-32, "Family 1, n=2"),
        (-8,  0, 32, "Family 2, n=2"),
        ( 0,  0,  0, "trivial"),
    ]
    for x, y, z, label in seeds:
        val = x**5 + 2*y**3 + z**3
        status = "✓" if val == 0 else f"✗ (={val})"
        print(f"  ({x:>4}, {y:>4}, {z:>4})  {status}  [{label}]")

    print("\nDone.")


if __name__ == "__main__":
    main()
